---
- name: Install prerequisite packages
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
      - wget
    state: present
    update_cache: yes

- name: Add Elastic GPG key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elastic-keyring.gpg
  args:
    creates: /usr/share/keyrings/elastic-keyring.gpg

- name: Add Elastic repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/9.x/apt stable main"
    filename: elastic-9.x
    state: present

- name: Install Filebeat
  apt:
    name: filebeat
    state: present
    update_cache: yes

- name: Ensure Filebeat is started and enabled
  service:
    name: filebeat
    state: started
    enabled: yes

- name: Configure Filebeat
  copy:
    content: |
      filebeat.inputs:
        - type: filestream
          id: nginx-access
          enabled: true
          paths:
            - /var/log/nginx/access.log
          prospector.scanner.fingerprint.length: 64  

      output.logstash:
        hosts: ["192.168.56.11:5044"]
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'

- name: Add filebeat user to adm group
  user:
    name: filebeat
    groups: adm
    append: yes

- name: Ensure nginx log directory is accessible, then restart Filebeat
  file:
    path: /var/log/nginx
    mode: '0755' # Or '0750' if group is adm
  notify: Restart Filebeat