---
# Installs Nginx web server using the apt package manager
- name: Install Nginx using native apt module
  apt:
    name: nginx
    state: present     #"install if not already exist"

#Starts Nginx and ensures it starts automatically on reboot
- name: Ensure Nginx is started and enabled on boot
  service:
    name: nginx
    state: started
    enabled: yes
