---
# First, apply common settings to all nodes (Security, Updates)
- name: Apply common configuration to all nodes
  hosts: all
  become: yes
  tasks:
    # Running apt update on all machines, saying yes to prompts
    - name: Update apt package lists
      shell: apt update -y
      args:
        warn: false  # Suppress warnings about apt lists being outdated
        
    # Running apt upgrade on all machines, saying yes to prompts
    - name: Upgrade all apt packages
      shell: apt upgrade -y
      register: upgrade_result  # Optional: Store output for later checks


    #- name: Update apt cache
    #  apt:
    #    update_cache: yes
    #    cache_valid_time: 3600

# Setup the ELK stack
- name: Setup Elasticsearch and Kibana
  hosts: elk
  become: yes
  roles:
    - elasticsearch
    - kibana

# Setup Logstash
- name: Setup Logstash Pipeline
  hosts: logstash
  become: yes
  roles:
    - logstash

# Setup the monitored webserver
- name: Setup Webserver and Log Shippers
  hosts: webserver
  become: yes
  roles:
    - nginx
    - filebeat