---
# First, apply common settings to all nodes (Security, Updates)
- name: Apply common configuration to all nodes
  hosts: all
  become: yes
  tasks:

  # Run apt update & upgrade on all machines
  - name: Update apt cache and upgrade all packages
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: dist
    register: upgrade_result    # Ouput is stored in Ansible for later checks

# THE OFFICIAL ANSIBLE RULEBOOK STRUCTURE
# Points to other .yml files in the roles directory. These are the files that ansible-playbook will run.
# The ELK stack starts by installing Docker Engine. Then it installes elasticsearch and kibana through docker. 
- name: Install ELK Stack
  hosts: elk
  become: yes
  roles:
    - docker
    - elk

# The logstash role installs and configures Logstash to listen for incoming logs from Filebeat and forward them to Elasticsearch.
- name: Install Logstash
  hosts: logstash
  become: yes
  roles:
    - logstash

# The webserver role installs and configures Nginx to serve a simple webpage to be monitored.
- name: Install Nginx Web Server
  hosts: webserver
  become: yes
  roles:
    - nginx

# The filebeat role installs and configures Filebeat to monitor Nginx logs and send them to Logstash.
- name: Setup Filebeat on webserver
  hosts: webserver
  become: yes
  roles:
    - filebeat

# Finally, we configure the firewall on all nodes to allow necessary traffic for our ELK stack to function properly.
- name: Configure firewall on all nodes
  hosts: all
  become: yes
  roles:
    - firewall