---
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present

# --- ALL HOSTS ---
- name: Allow SSH on all hosts
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

# Loop through each VM and open up the application-specific ports defined in the host variables
- name: Allow host-specific application ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ custom_ufw_rules | default([]) }}"

- name: Enable the UFW firewall
  community.general.ufw:
    state: enabled
    policy: deny          # Deny all incoming traffic by default

- name: Ensure UFW service is started and enabled
  ansible.builtin.systemd:
    name: ufw
    state: started
    enabled: yes